# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d06fb43e3a00e8a0fe41faeb4069bfccae02c0be0f4904cc4e3646d9751833d576ff92abe8422ffb98303e252ee31f1dcada4abde746723185cdee2587228dba

test:
  secret_key_base: 94cff51bb3d068bea1ad82360bfa8878a7615b74bc68992d829becc0a8f9cd50f6c756cab31ee5e41d6f4cbadedb620430ce9cb60c978f442b1023457fbd7e49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
